# Generated by Django 4.2.2 on 2023-07-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_signup_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='photo',
            field=models.ImageField(upload_to='Dp/'),
        ),
    ]
