# Generated by Django 4.2.2 on 2023-07-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_signup_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='photo',
            field=models.ImageField(null=True, upload_to='Dp/'),
        ),
    ]
