# Generated by Django 4.2.2 on 2023-07-11 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='team_logos')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament_ancmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=450)),
                ('title', models.CharField(max_length=450)),
                ('date', models.DateTimeField()),
                ('total_no_of_teams', models.IntegerField()),
                ('description', models.CharField(max_length=450)),
                ('registration_open', models.BooleanField(default=False)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('available_slots', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='Tournament.team')),
            ],
        ),
    ]
