# Generated by Django 4.1.7 on 2023-07-20 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_signup_photo'),
        ('Tournament', '0002_tournamentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.signup'),
            preserve_default=False,
        ),
    ]
