# Generated by Django 4.1.7 on 2023-07-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0003_team_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TournamentRegistration',
        ),
    ]
