# Generated by Django 4.1.7 on 2023-07-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0004_delete_tournamentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament_ancmt',
            name='image',
            field=models.ImageField(default=1, upload_to='tournaments'),
            preserve_default=False,
        ),
    ]
