# Generated by Django 4.2.2 on 2023-07-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slots', '0002_booking_name_booking_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='payment',
            new_name='amount',
        ),
    ]
