# Generated by Django 4.2.2 on 2023-07-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slots', '0003_rename_payment_booking_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='turf',
            new_name='turf_id',
        ),
    ]
