# Generated by Django 4.1.7 on 2023-07-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slots', '0005_rename_turf_id_slot_turf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='description',
            field=models.CharField(max_length=100000),
        ),
    ]
