# Generated by Django 4.2.2 on 2023-07-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slots', '0007_booking_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='payment',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
