# Generated by Django 4.1.7 on 2023-07-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slots', '0008_rename_payment_booking_order_id_remove_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
