# Generated by Django 4.1.7 on 2023-07-18 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Slots', '0009_alter_booking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='turf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Slots.turf'),
        ),
    ]
