# Generated by Django 4.1.7 on 2023-07-22 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_signup_photo'),
        ('Slots', '0012_alter_booking_slot_alter_slot_turf'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.signup'),
            preserve_default=False,
        ),
    ]
