# Generated by Django 4.1.7 on 2023-07-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slots', '0013_slot_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='user',
        ),
    ]
