# Generated by Django 4.1.7 on 2023-07-23 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_signup_photo'),
        ('Slots', '0018_remove_slot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.signup'),
            preserve_default=False,
        ),
    ]
