# Generated by Django 4.1.7 on 2023-07-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slots', '0019_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
